version: '3'

services:

  mongo1: # Primary mongo server
    image: "mongo-main:latest"
    build: ./mongo-GVDrs-1
    networks: 
      - mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-1:/data/db
    
  mongo2: #Secondary mongo server
    image: "mongo2:latest"
    build: ./mongo-GVDrs-1
    command: --replSet GVDrs --bind_ip_all --oplogSize 50
    networks: 
      - mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo-data-2:/data/db

  mongo3: #Secondary mongo server (Arbiter)
    image: "mongo3:latest"
    build: ./mongo-GVDrs-1
    command: --replSet GVDrs --bind_ip_all --oplogSize 50
    networks: 
      - mongo
    ports:
      - "27019:27017"
    volumes:
      - mongo-data-3:/data/db

  setup-GVDrs:
    image: "setup-rs"
    build: ./setup
    networks: 
      - mongo
    depends_on: 
      - "mongo1"
      - "mongo2"
      - "mongo3"
networks: 
  mongo:
    driver:  bridge
  
volumes:
  mongo-data-1:
    external: false
  mongo-data-2:
    external: false
  mongo-data-3:
    external: false


